### ISSUE TITLE
Initialization error: "Sentence root is not a be-verb"

### ISSUE THREAD

**Issue by sfelshin** [infolab-csail/whoami#130] opened 2019-01-10 18:12 UTC
I'm getting this error when trying to run Whoami:
```
whoami$ python scripts/run.py
Loading spaCy
Done loading
from whoami.query import get_assertion_definitions, get_question_definitions
from whoami.query import get_assertion_definitions, get_question_definitions []
ERROR:root:Sentence root is not a be-verb
Traceback (most recent call last):
  File "scripts/run.py", line 45, in <module>
    entry, tree = get_assertion_definitions(sentence, subject=synonyms, get_rep=True)
  File "build/bdist.linux-x86_64/egg/whoami/query.py", line 43, in get_assertion_definitions
    entry = extract_assertion(assertion, subject=subject)
  File "build/bdist.linux-x86_64/egg/whoami/defextract.py", line 171, in extract_assertion
    raise ParseError('Sentence root is not a be-verb')
ParseError: Sentence root is not a be-verb
```
Note that the error occurs on initialization, before trying to analyze any sentences.  Does Whoami try to analyze sentences as part of initialization?

The error "Sentence root is not a be-verb" would be appropriate if we were trying to analyze a sentence of the wrong form, e.g., "Callisto orbits around Jupiter" rather than "Callisto is a moon".  Although most Wikipedia articles' first sentences are of the form "_article_ is/are/was/were ...", some are not, e.g., the (trimmed) first sentence for [Polis](https://en.wikipedia.org/wiki/Polis) is "Polis, literally means city in Greek."  (The bogus comma after Polis is _sic_.)  So the error may occur legitimately.  But not during initialization!

**Comment by davidmv74** [comment] 2019-03-18 14:52
Looking at the latest build of the backend and the associated logs, I see that there were about 663,243 cases of raised ParseErrors because of the sentence root not being a be-verb. This is about 10% of articles which are not disambigs or redirects. 

There was an issue with build_types.py which uses whoami in order to create types tables for the backend, in which these errors were preventing updates to the table. 

There was another issue where the first paragraph was an empty string, caused by a number of articles having disambiguation statements before the first "real" paragraph. 

Both of these issues are being addressed through a PR in WikipediaBase.

**Comment by hanryhu** [comment] 2019-09-25 19:39
@sfelshin, I think this is a user error.  Where in the documentation does it say to run
```
from whoami.query import get_assertion_definitions, get_question_definitions
```
?

From what I can see, your input statement is not needed.  Whoami is trying to analyze this import as a sentence, and naturally giving an error when it tries to parse it.  The script already performs this import, so the user doesn't need to worry about it.  A working whoami session looks like this:
```
python scripts/run.py
Loading spaCy
Done loading
Callisto is a moon
Callisto is a moon []
['moon']
[subject: Callisto [def: moon]]
```
Unrelatedly, this script is still in python2.

**Comment by sfelshin** [comment] 2019-09-25 23:08
> @sfelshin, I think this is a user error.  Where in the documentation does it say to run
> ```
> from whoami.query import get_assertion_definitions, get_question_definitions
> ```

@hanryhu, it says that under [Usage](https://github.com/infolab-csail/whoami#usage):
> Example:
> ```
> >>> from whoami.query import get_assertion_definitions, get_question_definitions
> ```

What it does _not_ say is to run python as 
```
$ python scripts/run.py
```
In fact, it doesn't say anything at all about how to enter python, which is a flaw in the README. To be honest, I'm not sure where I got `$ python scripts/run.py` from although there is an old Slack post from Pond from Jan 17, 2018 that said:
> @Steph If all you need is to be able to play with whoami, I find script/run.py pretty sufficient

I see that if I do
```
$ python
from whoami.query import get_assertion_definitions, get_question_definitions
```
I can then run whoami on sentences.

So, please take this issue as a request to clarify the README and to take a look at `run.py` to see if it provides value, and either fix it or remove it accordingly.

As for your point about python2, please note that we updated the WikipediaBase installation instructions (in https://github.com/infolab-csail/WikipediaBase/pull/441, still not merged) with specialized instructions for python 3.  Either whoami should get the same update or we should Do Something to make us not need the specialized instructions.

**Comment by hanryhu** [comment] 2019-10-21 15:16
> As for your point about python2, please note that we updated the WikipediaBase installation instructions (in [infolab-csail/WikipediaBase#441](https://github.com/infolab-csail/WikipediaBase/pull/441), still not merged) with specialized instructions for python 3. Either whoami should get the same update or we should Do Something to make us not need the specialized instructions.

@sfelshin , I don't see any updates related to python 3 in that PR.  There is an update to the wikidata README, but it doesn't look related to python 3.  Did you mean https://github.com/infolab-csail/WikipediaBase/pull/386, which updates the README with extra information on running python 3 in emacs?

**Comment by sfelshin** [comment] 2019-10-21 17:03
@hanryhu, neither of those, and I'm not sure which PR I meant. :open_mouth: But note that the same changes were made in a different `README.md` in https://github.com/infolab-csail/annotation-tool/pull/23/files.

**Comment by hanryhu** [comment] 2019-10-31 17:11
@sfelshin Looks like the change in that README doesn't need to be ported because in the `whoami` README, we simply say "use a virtual environment" without going into python version-specific details.

**Comment by hanryhu** [comment] 2019-10-31 17:12
Closing this issue because it is a red-herring for https://github.com/infolab-csail/whoami/issues/118.

**Closed by hanryhu** 2019-10-31 17:12 UTC
Labels: bug, help wanted, priority/high

**Comment by sfelshin** [comment] 2019-10-31 18:55
> @sfelshin Looks like the change in that README doesn't need to be ported because in the whoami README, we simply say "use a virtual environment" without going into python version-specific details.

@hanryhu, my point was that if you just say `mkvirtualenv`, you won't get a Python 3 virtualenv.  You have to explicitly ask for a Python 3 virtualenv on the command line.  If your point is that people who use Python 3 should be expected to know they have to specify the version on the command line without being told, then okay ... but I will note that some non-python people (like me 😞) may follow installation instructions pretty blindly.
