### ISSUE TITLE
Include all definitions for sentences that include the form "noun + verb + prep. phrase"

### ISSUE THREAD

**Issue by shu98** [infolab-csail/whoami#104] opened 2018-01-12 20:22 UTC
For example
> Titanic is a musical with music and lyrics by Maury Yeston and a book by Peter Stone that opened on Broadway in 1997.

Whoami returns [u'musical']. Correct answer is [u'musical', u'book']

> Sarah is a student studying in Italy and a spy working for America.

Whoami returns [u'student']. Correct answer is [u'student', u'spy']
Consider: should it also include definitions like 'Italian student' or 'American spy'? 

Refer to [this](https://github.com/infolab-csail/WikipediaBase/issues/281#issuecomment-357341547) comment

**Comment by pondpremt** [comment] 2018-01-13 11:31
The first one is a spacy problem. There should be a "conj" arch from "musical" to "book", since it's "a musical ... and a book ...". But spacy incorrectly attaches "book" with  "Maury Yeston". In other words, it thinks that the lyrics are by Yeston and a book. 

I'm not sure about the second one. The parse looks fine. I'll need to look into that once I have whoami installed

**Comment by pondpremt** [comment] 2018-01-16 20:01
Ah, the cause for the second sentence is also bad parsing. Looks like `spacy 1.8.0` attaches "spy" to "Italy", meaning that Sarah is studying in Italy and in a spy, which is non-sensical. Feel free to close this issue

**Closed** 2018-01-16 20:44 UTC
